"use client";

import { useState } from "react";
import { FileText, Loader2, Check } from "lucide-react";
import { Button } from "@/components/ui/button";

interface DocxExportProps {
  title: string;
  sections: { heading: string; content: string }[];
  filename?: string;
}

export function DocxExport({ title, sections, filename }: DocxExportProps) {
  const [exporting, setExporting] = useState(false);
  const [done, setDone] = useState(false);

  const handleExport = async () => {
    setExporting(true);
    setDone(false);

    try {
      // Build a rich HTML document that can be opened in Word
      const html = `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>${title}</title>
<style>
  body { font-family: 'Times New Roman', serif; font-size: 12pt; line-height: 1.6; max-width: 700px; margin: 40px auto; color: #1a1a1a; }
  h1 { font-size: 18pt; font-weight: bold; margin-bottom: 24px; color: #111; }
  h2 { font-size: 14pt; font-weight: bold; margin-top: 28px; margin-bottom: 12px; color: #222; border-bottom: 1px solid #ddd; padding-bottom: 4px; }
  p { margin-bottom: 12px; text-align: justify; }
  table { width: 100%; border-collapse: collapse; margin: 16px 0; font-size: 11pt; }
  th, td { border: 1px solid #999; padding: 6px 10px; text-align: left; }
  th { background: #f0f0f0; font-weight: bold; }
  .note { font-size: 10pt; color: #666; font-style: italic; margin-top: 8px; }
  .stat { font-family: 'Courier New', monospace; font-size: 11pt; }
  .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #ddd; font-size: 10pt; color: #888; }
</style>
</head>
<body>
<h1>${title}</h1>
${sections.map((s) => `<h2>${s.heading}</h2>\n<div>${s.content.split("\n").map((line) => line.trim() ? `<p>${line}</p>` : "").join("")}</div>`).join("\n")}
<div class="footer">
  <p>Generated by MarTech Open Hub · ${new Date().toLocaleDateString("zh-CN")}</p>
</div>
</body>
</html>`;

      const blob = new Blob([html], { type: "text/html;charset=utf-8" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = filename || `${title.replace(/\s+/g, "-")}-${Date.now()}.html`;
      a.click();
      URL.revokeObjectURL(url);
      setDone(true);
      setTimeout(() => setDone(false), 3000);
    } catch (e) {
      console.error("Export failed:", e);
    } finally {
      setExporting(false);
    }
  };

  return (
    <Button variant="outline" size="sm" onClick={handleExport} disabled={exporting}
      className="h-8 px-3 text-xs border-[var(--border)] text-[var(--text-secondary)] hover:bg-[var(--bg-card-hover)]">
      {exporting ? <Loader2 className="w-3 h-3 mr-1 animate-spin" /> : done ? <Check className="w-3 h-3 mr-1 text-[var(--success)]" /> : <FileText className="w-3 h-3 mr-1" />}
      {done ? "已导出" : exporting ? "生成中..." : "导出 .html"}
    </Button>
  );
}
